site_name: Shichao's Notes
site_description: Shichao's Notes
site_url: https://notes.shichao.io
repo_url: https://github.com/shichao-an/notes
theme: yeti
pages:
  - ['index.md', 'Home']
  - ['apue/ch1.md', 'APUE', 'Chapter 1. UNIX System Overview']
  - ['apue/ch2.md', 'APUE', 'Chapter 2. UNIX Standardization and Implementations']
  - ['apue/ch3.md', 'APUE', 'Chapter 3. File I/O']
  - ['apue/ch4.md', 'APUE', 'Chapter 4. Files and Directories']
  - ['utlk/ch1.md', 'UTLK', 'Chapter 1. Introduction']
  - ['utlk/ch2.md', 'UTLK', 'Chapter 2. Memory Addressing']
  - ['unp/ch1.md', 'UNP', 'Chapter 1. Introduction']
  - ['golang/index.md', 'Golang']
  - ['bash/index.md', 'Bash']
