site_name: Shichao's Notes
site_description: Shichao's Notes
site_url: https://notes.shichao.io
repo_url: https://github.com/shichao-an/notes
theme: flatly
pages:
  - ['index.md', 'Home']
  - ['apue/ch1.md', 'APUE', 'Chapter 1. UNIX System Overview']
  - ['apue/ch2.md', 'APUE', 'Chapter 2. UNIX Standardization and Implementations']
  - ['apue/ch3.md', 'APUE', 'Chapter 3. File I/O']
  - ['apue/ch4.md', 'APUE', 'Chapter 4. Files and Directories']
  - ['apue/ch5.md', 'APUE', 'Chapter 5. Standard I/O Library']
  - ['utlk/ch1.md', 'UTLK', 'Chapter 1. Introduction']
  - ['utlk/ch2.md', 'UTLK', 'Chapter 2. Memory Addressing']
  - ['unp/ch1.md', 'UNP', 'Chapter 1. Introduction']
  - ['unp/ch2.md', 'UNP', 'Chapter 2. The Transport Layer: TCP, UDP, and SCTP']
  - ['icnd1/part1.md', 'ICND', 'ICND1 Part I: Networking Fundamentals']
  - ['icnd2/part1.md', 'ICND', 'ICND2 Part I: LAN Switching']
  - ['tcpv1/ch1.md', 'TCPv1', 'Chapter 1. Introduction']
  - ['htae/index.md', 'Others', 'HTAE']
  - ['golang/index.md', 'Others', 'Go']
  - ['bash/index.md','Others', 'Bash']
  - ['c/index.md', 'Others', 'C']
  - ['iptables/index.md','Others', 'iptables']
  - ['nginx/index.md','Others', 'Nginx']
  - ['vim/index.md','Others', 'Vim']
